name: Test -CI

on:
  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    environment: PPE
      
    steps:
     - name: Display the env name
       run: | 
           echo "name is ${{vars.USERNAME}}"
           echo "password is ${{secrets.PASSWORD}}"

    
